# Makefile for Programming Project 1
#
# CSCI 21, Spring 2014
#
# Programmer: Sebastian Rollins Brenton
#

# Target for Programming Project 1
# Date completed: 2-13-2014
# Date updated: 2-21-2014

FLAGS = -Wall -Wextra -Werror -pedantic


pj1: ProgrammingProject1

ProgrammingProject1: ProgrammingProject1.cpp
	g++ $(FLAGS) -o ProgrammingProject1 ProgrammingProject1.cpp