# Makefile for programming challenges
#
# CSCI 21, Spring 2014
#
# Programmer: Sebastian Rollins Brenton
#

# Target for programming challenge 3
# Date completed: 2-3-2014
# Date updated: 2-5-2014

all: challenge-1 challenge-2 challenge-3 challenge-4 challenge-5

challenge-1: chng1.cpp
	g++ -o chng1 chng1.cpp

challenge-2: chng2.cpp
	g++ -o chng2 chng2.cpp

challenge-3: chng3.cpp
	g++ -o chng3 chng3.cpp

challenge-4: chng4.cpp
	g++ -o chng4 chng4.cpp

challenge-5: chng5.cpp
	g++ -o chng5 chng5.cpp