# Makefile for programming challenges
#
# CSCI 21, Spring 2014
#
# Programmer: Sebastian Rollins Brenton
#

# Target for programming challenge 3
# Date completed: 2-3-2014
challenge-1: chng1.cpp
	g++ -o chng1 chng1.cpp
challenge-3: challenge-3.cpp
	g++ -o challenge-3 challenge-3.cpp
challenge-4: chng4.cpp
	g++ -o chng4 chng4.cpp