# Makefile for programming challenges
#
# CSCI 21, Spring 2014
#
# Programmer: Sebastian Rollins Brenton
#

# Target for programming challenge 3
# Date completed: 2-3-2014
# Date updated: 3-31-2014

FLAGS = -Wall -Wextra -Werror -pedantic

all: pc15 pc14 pc13 pc12 pc11 pc10 pc9 pc8 pc7 pc6 pc5 pc4 pc3 pc2 pc1


pc15: Challenge15/chng15

Challenge15/chng15: Challenge15/chng15.cpp
	g++ $(FLAGS) -o Challenge15/chng15 Challenge15/chng15.cpp


pc14: Challenge14/chng14

Challenge14/chng14: Challenge14/chng14.cpp
	g++ $(FLAGS) -o Challenge14/chng14 Challenge14/chng14.cpp


pc13: Challenge13/chng13

Challenge13/chng13: Challenge13/chng13.cpp
	g++ $(FLAGS) -o Challenge13/chng13 Challenge13/chng13.cpp


pc12: Challenge12/chng12

Challenge12/chng12: Challenge12/chng12.cpp
	g++ $(FLAGS) -o Challenge12/chng12 Challenge12/chng12.cpp


pc11: Challenge11/chng11

Challenge11/chng11: Challenge11/chng11.cpp
	g++ $(FLAGS) -o Challenge11/chng11 Challenge11/chng11.cpp


pc10: Challenge10/chng10

Challenge10/chng10: Challenge10/chng10.cpp
	g++ $(FLAGS) -o Challenge10/chng10 Challenge10/chng10.cpp


pc9: Challenge9/chng9

Challenge9/chng9: Challenge9/chng9.cpp
	g++ $(FLAGS) -o Challenge9/chng9 Challenge9/chng9.cpp


pc8: Challenge8/chng8

Challenge8/chng8: Challenge8/chng8.cpp
	g++ $(FLAGS) -o Challenge8/chng8 Challenge8/chng8.cpp


pc7: Challenge7/chng7

Challenge7/chng7: Challenge7/chng7.cpp
	g++ $(FLAGS) -o Challenge7/chng7 Challenge7/chng7.cpp


pc6: Challenge6/chng6

Challenge6/chng6: Challenge6/chng6.cpp
	g++ $(FLAGS) -o Challenge6/chng6 Challenge6/chng6.cpp


pc5: Challenge5/chng5

Challenge5/chng5: Challenge5/chng5.cpp
	g++ $(FLAGS) -o Challenge5/chng5 Challenge5/chng5.cpp


pc4: Challenge4/chng4

Challenge4/chng4: Challenge4/chng4.cpp
	g++ $(FLAGS) -o Challenge4/chng4 Challenge4/chng4.cpp


pc3: Challenge3/chng3

Challenge3/chng3: Challenge3/chng3.cpp
	g++ $(FLAGS) -o Challenge3/chng3 Challenge3/chng3.cpp


pc2: Challenge2/chng2

Challenge2/chng2: Challenge2/chng2.cpp
	g++ $(FLAGS) -o Challenge2/chng2 Challenge2/chng2.cpp


pc1: Challenge1/chng1

Challenge1/chng1: Challenge1/chng1.cpp
	g++ $(FLAGS) -o Challenge1/chng1 Challenge1/chng1.cpp







